INSERT INTO TB_USER(USER_ID, PASSWORD, ROLE_ID, USER_NAME, EMAIL, POINT, GENDER) VALUES('admin', 'admin', 'ADMIN', '운영자', 'admin@admin.com', 0, 'F');
INSERT INTO TB_USER(USER_ID, PASSWORD, ROLE_ID, USER_NAME, EMAIL, POINT, GENDER) VALUES('manager', 'manager', 'MANAGER', '관리자', 'manager@manager.com', 0,'M');
INSERT INTO TB_USER(USER_ID, PASSWORD, ROLE_ID, USER_NAME, EMAIL, POINT, GENDER) VALUES('user', 'user', 'USER', '일반사용자', 'user@user.com', 0, 'M');

INSERT INTO SECURITY_ROLE(ROLE_ID, ROLE_NAME, USE_YN, EDITABLE) VALUES('ADMIN', '운영자', 'Y', 'N');
INSERT INTO SECURITY_ROLE(ROLE_ID, ROLE_NAME, USE_YN, EDITABLE) VALUES('MANAGER', '관리자', 'Y', 'Y');
INSERT INTO SECURITY_ROLE(ROLE_ID, ROLE_NAME, USE_YN, EDITABLE) VALUES('USER', '일반사용자', 'Y', 'Y');

INSERT INTO SECURITY_ROLE_HIERARCHY(PARENT_ROLE_ID, ROLE_ID, ROLE_NAME) VALUES(NULL, 'ADMIN', '운영자');
INSERT INTO SECURITY_ROLE_HIERARCHY(PARENT_ROLE_ID, ROLE_ID, ROLE_NAME) VALUES('ADMIN', 'MANAGER', '관리자');
INSERT INTO SECURITY_ROLE_HIERARCHY(PARENT_ROLE_ID, ROLE_ID, ROLE_NAME) VALUES('MANAGER', 'USER', '일반사용자');

INSERT INTO SECURITY_ROLE_URL(URL, ACCESS_ROLE, PRIORITY) VALUES('/admin/*', 'ADMIN', 0);
INSERT INTO SECURITY_ROLE_URL(URL, ACCESS_ROLE, PRIORITY) VALUES('/board/*', 'USER', 0);
INSERT INTO SECURITY_ROLE_URL(URL, ACCESS_ROLE, PRIORITY) VALUES('/*', 'USER', 10);